/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author SALA16
 */
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        meApplication = new javax.swing.JMenu();
        miCloseSession = new javax.swing.JMenuItem();
        miSeparatorApp = new javax.swing.JPopupMenu.Separator();
        miExitApp = new javax.swing.JMenuItem();
        mePrices = new javax.swing.JMenu();
        miPricesAdmin = new javax.swing.JMenuItem();
        miPricesAdd = new javax.swing.JMenuItem();
        meProducts = new javax.swing.JMenu();
        miProductsAdmin = new javax.swing.JMenuItem();
        miProductsAdd = new javax.swing.JMenuItem();
        meUsers = new javax.swing.JMenu();
        miUsersAdmin = new javax.swing.JMenuItem();
        miUsersAdd = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        meApplication.setText("Aplicación");

        miCloseSession.setText("Cerrar Sesión");
        miCloseSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCloseSessionActionPerformed(evt);
            }
        });
        meApplication.add(miCloseSession);
        meApplication.add(miSeparatorApp);

        miExitApp.setText("Salir");
        miExitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitAppActionPerformed(evt);
            }
        });
        meApplication.add(miExitApp);

        jMenuBar1.add(meApplication);

        mePrices.setText("Precios");

        miPricesAdmin.setText("Administrar");
        mePrices.add(miPricesAdmin);

        miPricesAdd.setText("Agregar");
        mePrices.add(miPricesAdd);

        jMenuBar1.add(mePrices);

        meProducts.setText("Productos");

        miProductsAdmin.setText("Administrar");
        miProductsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductsAdminActionPerformed(evt);
            }
        });
        meProducts.add(miProductsAdmin);

        miProductsAdd.setText("Agregar");
        miProductsAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductsAddActionPerformed(evt);
            }
        });
        meProducts.add(miProductsAdd);

        jMenuBar1.add(meProducts);

        meUsers.setText("Usuarios");

        miUsersAdmin.setText("Administrar");
        meUsers.add(miUsersAdmin);

        miUsersAdd.setText("Agregar");
        meUsers.add(miUsersAdd);

        jMenuBar1.add(meUsers);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProductsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductsAdminActionPerformed
        ProductsAdmin pa = new ProductsAdmin();
        this.desktopPane.add(pa);
        pa.setVisible(true);
    }//GEN-LAST:event_miProductsAdminActionPerformed

    private void miCloseSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCloseSessionActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miCloseSessionActionPerformed

    private void miExitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitAppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miExitAppActionPerformed

    private void miProductsAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductsAddActionPerformed
        ProductsAdd pa = new ProductsAdd();
        this.desktopPane.add(pa);
        pa.setVisible(true);
    }//GEN-LAST:event_miProductsAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu meApplication;
    private javax.swing.JMenu mePrices;
    private javax.swing.JMenu meProducts;
    private javax.swing.JMenu meUsers;
    private javax.swing.JMenuItem miCloseSession;
    private javax.swing.JMenuItem miExitApp;
    private javax.swing.JMenuItem miPricesAdd;
    private javax.swing.JMenuItem miPricesAdmin;
    private javax.swing.JMenuItem miProductsAdd;
    private javax.swing.JMenuItem miProductsAdmin;
    private javax.swing.JPopupMenu.Separator miSeparatorApp;
    private javax.swing.JMenuItem miUsersAdd;
    private javax.swing.JMenuItem miUsersAdmin;
    // End of variables declaration//GEN-END:variables
}
